[package]
name = "squint"
version = "0.1.0"
edition = "2024"

[dependencies]
block2 = "0.6"
clap = { version = "4.6", features = ["derive"] }
csscolorparser = "0.9"
dispatch2 = "0.3"
jiff = "0.2.38"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
pulldown-cmark = { version = "0.13.4", default-features = false }
